import pandas as pd
import numpy as np

def generate_synthetic_from_real(df: pd.DataFrame, perturbation_level: float = 0.5) -> pd.DataFrame:
    """
    Takes a real dataset and perturbs it to simulate a fake/synthetic dataset.
    This creates the negative class for our meta-classifier since real bad/fake Kaggle
    data is hard to find in bulk.
    
    perturbation_level: 0.0 to 1.0 (How aggressively to ruin the dataset)
    """
    if df.empty:
        return df

    syn_df = df.copy()
    n_rows, n_cols = syn_df.shape
    
    num_cols = syn_df.select_dtypes(include=[np.number]).columns
    cat_cols = syn_df.select_dtypes(exclude=[np.number]).columns

    # 1. Break correlations by shuffling columns independently
    # If a dataset is generated by marginal distributions only, it loses correlation.
    if len(num_cols) > 1:
        cols_to_shuffle = int(len(num_cols) * perturbation_level)
        shuffle_candidates = np.random.choice(num_cols, cols_to_shuffle, replace=False)
        for col in shuffle_candidates:
            # Independent shuffle
            syn_df[col] = syn_df[col].sample(frac=1).reset_index(drop=True)

    # 2. Inject exact duplicate rows (Common in cheap scrapers/generators)
    if perturbation_level > 0.3:
        n_dupes = int(n_rows * (perturbation_level / 2)) # up to 50% duplicates
        if n_dupes > 0:
            dupes = syn_df.sample(n=n_dupes, replace=True)
            syn_df = pd.concat([syn_df, dupes], ignore_index=True)
            
    # 3. Add noise / Destroy Benford's Law + natural distributions
    for col in num_cols:
        if np.random.rand() < perturbation_level:
            # Instead of natural distribution, replace with uniform random between min and max
            col_min, col_max = syn_df[col].min(), syn_df[col].max()
            if not pd.isna(col_min) and not pd.isna(col_max):
                syn_df[col] = np.random.uniform(col_min, col_max, size=len(syn_df))
                
            # Randomly inject rounded numbers (like exact integers or .00)
            if np.random.rand() < 0.5:
                idx_to_round = np.random.choice(syn_df.index, int(len(syn_df) * perturbation_level), replace=False)
                syn_df.loc[idx_to_round, col] = np.round(syn_df.loc[idx_to_round, col] / 10) * 10
                
    # 4. Modify Categorical distributions
    for col in cat_cols:
        if np.random.rand() < perturbation_level:
            # Flatten categorical distributions
            unique_vals = df[col].dropna().unique()
            if len(unique_vals) > 0:
                syn_df[col] = np.random.choice(unique_vals, size=len(syn_df), replace=True)

    # 5. Inject exact missing value block patterns
    if perturbation_level > 0.4:
         # Simulating a scraper breaking half-way
         missing_col = np.random.choice(syn_df.columns)
         missing_idx = np.random.choice(syn_df.index, int(len(syn_df) * 0.4), replace=False)
         syn_df.loc[missing_idx, missing_col] = np.nan

    # Ensure it's roughly same size if we added dupes, maybe sample back down
    if len(syn_df) > n_rows and np.random.rand() < 0.5:
        syn_df = syn_df.sample(n=n_rows).reset_index(drop=True)

    return syn_df

def generate_toy_datasets(output_dir='data'):
    """Generate toy real and synthetic data for CI/CD or local test."""
    import os
    os.makedirs(f"{output_dir}/real", exist_ok=True)
    os.makedirs(f"{output_dir}/synthetic", exist_ok=True)
    
    # Toy Real
    df_real = pd.DataFrame({
        'A': np.random.normal(50, 15, 1000),
        'B': np.random.normal(20, 5, 1000) * 2 + 5, # Correlated with A theoretically
        'C': np.random.exponential(2, 1000), # Has specific distribution
        'Category': np.random.choice(['Yes', 'No', 'Maybe'], 1000, p=[0.7, 0.2, 0.1]) # Uneven Pareto-ish dist
    })
    # Make 'A' follow benfords roughly by making it exponential spanning orders of magnitude
    df_real['Benford_Col'] = 10 ** np.random.uniform(1, 4, 1000)
    
    df_real.to_csv(f"{output_dir}/real/sample_real.csv", index=False)
    
    # Generate a fake from it
    df_fake = generate_synthetic_from_real(df_real, perturbation_level=0.8)
    df_fake.to_csv(f"{output_dir}/synthetic/sample_fake.csv", index=False)
    
    print("Generated toy datasets.")

if __name__ == "__main__":
    generate_toy_datasets()
